### ISSUE TITLE
#team-106-the-kingsnakes

### ISSUE THREAD

**Issue by krys2fa** [chelmerrox/Project-3-Positioning-and-Floating-Elements#1]
Great job finishing the Html structure. 👍 
It is well organized and structured as well. 
 
A few things to note:
- validate your Html page often (especially when working with elements like figcaption, h and span tags)
- change the "theory of inflation" image to a background image.
- add  "margin: 0 auto;  max-width: 1440px; " to your body selector in your stylesheet.

All the best as you continue with the project.

**Comment by chelmerrox** [comment]
Thanks for the review! 

I've resolved the issues. 

Thanks again.
