### ISSUE TITLE
#team-106-the-kingsnakes

### ISSUE THREAD

**Issue by krys2fa** [chelmerrox/Project-3-Positioning-and-Floating-Elements#2]
Impressive job on your progress so far. 👏 

A few things to note:
- add margin or padding to the left of the "Theory of Inflation" section to centre it.
- compare the font and line-height of your page to that of the original page.
- add rounded borders to your social media icons.
- reduce the width of borders for "Thanks for reading the Times" section.

Feel free to implement the suggested changes after you have completed the rest of the project.

Best of luck. 🤞

**Comment by chelmerrox** [comment]
I've resolved these issues. Thanks for the review!

**Comment by rammazzoti2000** [comment]
@krys2fa Please do not open new Pull Request each time you request a review, is very hard to keep track of the review from the previous tse, instead when asked for another review use the same pull request where the tse was reviewing in the first place.
Open new pull request only when asked too, thank you.
